/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.lcs.Bibilava;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bas=0x7f020000;
        public static final int best=0x7f020001;
        public static final int bombe=0x7f020002;
        public static final int bombe1=0x7f020003;
        public static final int cinq=0x7f020004;
        public static final int default_icon=0x7f020005;
        public static final int deux=0x7f020006;
        public static final int droite=0x7f020007;
        public static final int game=0x7f020008;
        public static final int gauche=0x7f020009;
        public static final int haut=0x7f02000a;
        public static final int huit=0x7f02000b;
        public static final int jarvis=0x7f02000c;
        public static final int mur=0x7f02000d;
        public static final int neuf=0x7f02000e;
        public static final int nourr=0x7f02000f;
        public static final int pause2=0x7f020010;
        public static final int quatre=0x7f020011;
        public static final int queueb=0x7f020012;
        public static final int queued=0x7f020013;
        public static final int queueg=0x7f020014;
        public static final int queueh=0x7f020015;
        public static final int score=0x7f020016;
        public static final int sept=0x7f020017;
        public static final int simplec=0x7f020018;
        public static final int simpleh=0x7f020019;
        public static final int simplev=0x7f02001a;
        public static final int six=0x7f02001b;
        public static final int teteb=0x7f02001c;
        public static final int teted=0x7f02001d;
        public static final int teteg=0x7f02001e;
        public static final int teteh=0x7f02001f;
        public static final int trois=0x7f020020;
        public static final int un=0x7f020021;
        public static final int zero=0x7f020022;
    }
    public static final class id {
        public static final int ambony=0x7f060004;
        public static final int bas=0x7f06000a;
        public static final int bouton=0x7f060002;
        public static final int choix=0x7f060000;
        public static final int droite=0x7f060009;
        public static final int gauche=0x7f060007;
        public static final int glisser=0x7f060001;
        public static final int haut=0x7f060006;
        public static final int pause=0x7f060008;
        public static final int terrain=0x7f060003;
        public static final int touche=0x7f060005;
    }
    public static final class layout {
        public static final int choix_xml=0x7f030000;
        public static final int terrain_xml=0x7f030001;
    }
    public static final class raw {
        public static final int son_depl=0x7f040000;
        public static final int son_mange=0x7f040001;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
    }
}
